// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Логин",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход в аккаунт",
                "parameters": [
                    {
                        "description": "login info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.loginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.loginResp"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Logout",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход из аккаунта",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/registration": {
            "post": {
                "description": "Регистрация",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация",
                "parameters": [
                    {
                        "description": "Информация о пользователе",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.Users"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.registerResp"
                        }
                    }
                }
            }
        },
        "/delete-MtM/{idDye}/colorant/{idColorant}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удалить краситель из заявки",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colorant-Dye"
                ],
                "summary": "Удалить краситель из заявки",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "idDye",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID красителя",
                        "name": "idColorant",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Краситель был удален из заявки",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/list_of_colorants": {
            "get": {
                "description": "Вывести список красителей",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colorants"
                ],
                "summary": "Вывести список красителей",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "404": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    }
                }
            }
        },
        "/new_colorant": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Создать краситель",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colorants"
                ],
                "summary": "Создать краситель",
                "parameters": [
                    {
                        "description": "Информация о красителе",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "404": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    }
                }
            }
        },
        "/delete-service/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удалить краситель",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colorants"
                ],
                "summary": "Удалить краситель",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID красителя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "404": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    }
                }
            }
        },
        "/update_colorants/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновить краситель",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colorants"
                ],
                "summary": "Обновить краситель",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID красителя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Информация о красителе",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "404": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    }
                }
            }
        },
        "/{id}": {
            "get": {
                "description": "Показать краситель по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colorants"
                ],
                "summary": "Показать краситель по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID красителя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "404": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    }
                }
            }
        },
        "/colorant/{id}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Добавить краситель в заявку",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colorants"
                ],
                "summary": "Добавить краситель в заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID красителя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "404": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    }
                }
            }
        },
        "/{id}/addImage": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Добавить изображение к красителю",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colorants"
                ],
                "summary": "Добавить изображение к красителю",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID красителя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Файл изображения",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "404": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/ds.ColorantsAndOtheres"
                        }
                    }
                }
            }
        },
        "/list_of_dyes": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Вывести список заявок",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dyes"
                ],
                "summary": "Вывести список заявок",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    },
                    "404": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    }
                }
            }
        },
        "/delete-dye/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удалить заявку",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dyes"
                ],
                "summary": "Удалить заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    },
                    "404": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    }
                }
            }
        },
        "/update_dyes/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновить заявку",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dyes"
                ],
                "summary": "Обновить заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Информация о заявке",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    },
                    "404": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    }
                }
            }
        },
        "/dyeid/{id}/status/{status}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновить статус модератором",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dyes"
                ],
                "summary": "Обновить статус модератором",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
					{
                        "type": "string",
                        "description": "Статус",
                        "name": "status",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Информация о статусе",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.StatusData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    },
                    "404": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    }
                }
            }
        },
        "/formation-dye/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Сформировать заявку",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dyes"
                ],
                "summary": "Сформировать заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    },
                    "404": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/ds.Dyes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.loginReq": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "app.loginResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "app.registerResp": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "ds.ColorantsAndOtheres": {
            "type": "object",
            "properties": {
                "ID_Colorant": {
                    "type": "integer"
                },
                "Name": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "Description": {
                    "type": "string"
                },
                "Properties": {
                    "type": "string"
                },
                "Status": {
                    "type": "string"
                }
            }
        },
        "ds.Dyes": {
            "type": "object",
            "properties": {
                "ID_Dye": {
                    "type": "integer"
                },
                "User_ID": {
                    "type": "integer"
                },
                "Name": {
                    "type": "string"
                },
                "Status": {
                    "type": "string"
                },
                "CreationDate": {
                    "type": "string"
                },
                "FormationDate": {
                    "type": "string"
                },
                "Moderator": {
                    "type": "integer"
                },
                "CompletionDate": {
                    "type": "string"
                },
                "Price": {
                    "type": "integer"
                }
            }
        },
        "ds.StatusData": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "ds.Users": {
            "type": "object",
            "properties": {
                "Email_Address": {
                    "type": "string"
                },
                "ID_User": {
                    "type": "integer"
                },
                "Name": {
                    "type": "string"
                },
                "Login": {
                    "type": "string"
                },
                "Password": {
                    "type": "string"
                },
                "Phone": {
                    "type": "string"
                },
                "Role": {
                    "$ref": "#/definitions/role.Role"
                }
            }
        },
		"ds.Dye_Colorants": {
            "type": "object",
            "properties": {
                "ID_Dye": {
                    "type": "integer"
                },
                "ID_Colorant": {
                    "type": "integer"
                },
                "Percent_Content": {
                    "type": "float"
                }
            }
        },
        "role.Role": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-comments": {
                "Admin": "2",
                "Buyer": "0",
                "Manager": "1"
            },
            "x-enum-varnames": [
                "Buyer",
                "Manager",
                "Admin"
            ]
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Производство красок",
	Description:      "Colorants app",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}